using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class FiniteGroupGallery : PresentationGallery
{
    FiniteGroupGallery() : base("Finite Groups:", finiteGroups) { }
    
    // List of groups to be displayed, parameters are name, generators and relators.
    static readonly PresentationExample[] finiteGroups = {
        new PresentationExample("e", "The trivial group", "", "", "A very simple group", "https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
        new CyclicGroup(),
        new PresentationExample("V<sub>4</sub>", "The Klein group", "a; b", "a^2; b^2; abAB", "The Klein group can be understood as all possible states of two light switches", "https://en.wikipedia.org/wiki/Klein_four-group"),
        new TorusGroup(),
        new DihedralGroup(),
        new SymmetricGroup(),
        new PresentationExample("Q<sub>8</sub>", "The quaternion group", "i; j", "i^4; jijI; ijiJ", "Just as the complex numbers are an extension of the real numbers, the quaternions are an extension of the complex numbers. Besides 1 and i, the quaternion group also uses letters j and k. The elements 1, i, j, and k form a finite group under multiplication.", "https://en.wikipedia.org/wiki/Quaternion_group"),
        new DicyclicGroup(),
        new PresentationExample("T ≅ A<sub>4</sub>", "The symmetry group of the tetrahedron", "s; t", "s^2; t^3; (st)^3", "The tetrahedron has multiple symmetries. Two of those are a rotation r along a vertical axis and a reflection s along a horizontal axis. The set of all symmetries forms a group, generated by r and s.", "https://en.wikipedia.org/wiki/Tetrahedral_symmetry"),
        new PresentationExample("O ≅ S<sub>4</sub>", "The symmetry group of the octahedron", "s; t", "s^2; t^3; (st)^4", "The octahedron has multiple symmetries. Two of those are a rotation r along a vertical axis and a reflection s along a horizontal axis. The set of all symmetries forms a group, generated by r and s.", "https://en.wikipedia.org/wiki/Octahedral_symmetry"),
        new PresentationExample("I ≅ A<sub>5</sub>", "The symmetry group of the icosahedron", "s; t", "s^2; t^3; (st)^5", "The icosahedron has multiple symmetries. Two of those are a rotation r along a vertical axis and a reflection s along a horizontal axis. The set of all symmetries forms a group, generated by r and s.", "https://en.wikipedia.org/wiki/Icosahedral_symmetry"),
        new PresentationExample("Rub<sub>2×2×2</sub>", "The group of the 2x2x2 Rubik's cube", "a; b; c", "a^4; b^4; c^4; ababa=babab; ababa = babab; bcbcb = cbcbc; abcba = bcbac; bcacb = cacba; cabac = abacb; (ac)^2(ab)^3(cb)^2", "We can interpret a rotation on a 2x2x2 Rubik's cube as an operation. Chaining together rotation gives new operation, forming a group", "https://mathoverflow.net/questions/72465/a-presentation-for-rubiks-cube-group"),
        //new MonsterGroup()
    };

}
